name: Docker Network Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Docker login step to authenticate with DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    # Build Docker image and tag it with the DockerHub username and commit SHA
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:${{ github.sha }} .

    # Push the image to DockerHub
    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Pull Docker image from DockerHub
      run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:${{ github.sha }}

    - name: Create Docker network
      run: docker network create my_custom_network

    - name: Run container 1
      run: docker run -d --name container1 --network my_custom_network ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:${{ github.sha }}

    - name: Run container 2
      run: docker run -d --name container2 --network my_custom_network ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:${{ github.sha }}

    - name: Verify container communication with curl
      run: docker exec container2 curl -s container1:5000

    - name: Inspect Docker network
      run: docker network inspect my_custom_network

