name: Docker Network Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t my-flask-app:${{ secrets.DOCKER_HUB_USERNAME }} .

    - name: Push Docker image to DockerHub
      run: docker push my-flask-app:${{ secrets.DOCKER_HUB_USERNAME }}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Pull Docker image
      run: docker pull my-flask-app:${{ secrets.DOCKER_HUB_USERNAME }}

    - name: Create Docker network
      run: docker network create my_custom_network

    - name: Run container 1
      run: docker run -d --name container1 --network my_custom_network my-flask-app:${{ secrets.DOCKER_HUB_USERNAME }}

    - name: Run container 2
      run: docker run -d --name container2 --network my_custom_network my-flask-app:${{ secrets.DOCKER_HUB_USERNAME }}

    - name: Verify container communication with curl
      run: docker exec container2 curl -s container1:5000

    - name: Inspect Docker network
      run: docker network inspect my_custom_network
